apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: library-api
type: Opaque
stringData:
  JWT_SECRET_KEY: "4oD+L5qG7wE9xR2bY8vN1mC0pA3zT6jK9sF4uH7yX+Q="
  SPRING_MONGODB_URI: "mongodb://emc:emc@mongodb:27017/library-db?authSource=admin"
