---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secret
  namespace: library-api
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgB4y4GQY4ky4Gm6fYNsXadGKHYkPrjD9xQNy9CZ+zC4SZSaNQA/nqzEeGqJOJBp5K3PirTH9PL1zQYUgJRwFdhVW843aB27RVT6rSAermfcS70O6BWDsBExkKTjJ/vO9NXzrflDRfNlY7OpQ4xRaZKat4qBZM1Q4cTZa/PO69itSedWzQWT6CELLKgn0Qh0hmkfn9LnHfABP7M/f1rf03tuWdr+5dn91LxFAROuT2HlFZqk2ufbhpS3wr/EUyfAYzZbk01OXZkFNipF+ZhF5e2CRWyl+31c2VTN826+sWf78AZDTDotOQm6AzJPF4FyxPHc0t8G8MmVXiDHeYt47xCqU0/kOvDJ2fLr3Y1DYLHL/y8bbJlzbI9m1lTAraE8yjbpsGQ3OAStB0qFsO4Oc+WGnX9RhssaXO7vNk2SZVzkQsQa3cIozmQMAdczMQ/WhoIfkbEw2NEOxZeppk1JhMgdnlseEor1hCtB5wqTYwPQNeFgV1Up/SSSmjhxVEfIGm03/vrhn6cglpPT6Ae9igkWyXV+zC/kV6KasNwQnWSmryMU+pWvIuGIIO67Mvkeoy6vbI4dQRHs5VxmJnRULEybn1O3NxttxDAFUpotBtQMmVsoMgr/4IGVpKFY+dE3Zjm44IDWkhmAGuJxC5eMarRDVxmEYmMkteIz7FUwwa5jABZK/W8fr3bVu1RMd4kyTPXPetGBrhl3/IyLhpY2U33plvQLRA==
    MONGO_INITDB_ROOT_USERNAME: AgB8C8Jr61hnLQ0nEHaxgvHR7HrfWwUwPhudDw8I/Q/Bwc5dHID0hfP+/D3207JXtKP93GY9X8/3YICF+2Q3H2es29y+p6SJUHIho/B6kwPXP2K/e9qubwWh3CU/N++OcP8dyBZamA66f5hOnWlDoLXr2094PS8HUMQH9W8H1xmwRGd8tP4m776YtYJtHJyTujtgQitAfLJzJc9DXi83dZc0B4UktoZaDExxkir1vzUs93eZccL0Vq5gW3y18HheB9+xcgTVRYmLPumi68z29blMfhb4Hrs4UNUDXMK2gDg0uA3RvLmp1B3OzomrfPZo9HES+jRmtlRmOiOb+eFslH4yCYOKw+rNrOE3yqug/cxgZ0LKdwb3Z96TF1DPtSHdiDhUmyW6k9eZX0Sij5oNmMvjJqiHAuFVqAG3e6gTQptPrLpR17Zsjf0e2SW3idSixTmEyaRN16KshW2SO35R1bAlqIbFdvZgSKK0p26TD9g0cB8vyaonXlP2RtNHleQDo2pgVrVw1znzfGY932H2WsPErcmT+NQHIeqmdQzXhOZJRxFhE/c3lrXYz3bgMc1fkb7iU70fAUyCXkKLHFpejGE/2PUyVLMSDzkKrMRsaidRwbTYgngAUODStb7bh3y0VORQwLo3Ehoonpm+UTLMWMcvHwtCg2uipLautX18Qy0jsdNGEnKU/xtw8C4xlZNxzrR5jGE=
  template:
    metadata:
      name: mongodb-secret
      namespace: library-api
    type: Opaque
