apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- mongodb/configmap.yaml
- mongodb/secret.yaml
- mongodb/service.yaml
- mongodb/statefulset.yaml
- backend/configmap.yaml
- backend/secret.yaml
- backend/service.yaml
- backend/deployment.yaml
- frontend/service.yaml
- frontend/deployment.yaml
- clusterissuer.yaml
- ingress.yaml

images:
- name: frikzy/library-api-backend
  newName: frikzy/library-api-backend
  newTag: da5778f472fff6a4a18043d74a58893e97287d53
- name: frikzy/library-api-frontend
  newName: frikzy/library-api-frontend
  newTag: da5778f472fff6a4a18043d74a58893e97287d53
