apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- mongodb/configmap.yaml
- mongodb/secret.yaml
- mongodb/service.yaml
- mongodb/statefulset.yaml
- backend/configmap.yaml
- backend/secret.yaml
- backend/service.yaml
- backend/deployment.yaml
- frontend/service.yaml
- frontend/deployment.yaml
- ingress.yaml

images:
- name: frikzy/library-api-backend
  newName: frikzy/library-api-backend
  newTag: 26a009322fbee1ff096f7d121aa5a57520e1b8af
- name: frikzy/library-api-frontend
  newName: frikzy/library-api-frontend
  newTag: 26a009322fbee1ff096f7d121aa5a57520e1b8af
